#include <stdio.h>
#include <string.h>
#include <stdlib.h>

int encryption(void);

int main()
{
    encryption();
    return 0;
}

int encryption(void)
{
    char word[7] = "success", cipher[7] = "", answer[7] = "";

    printf("\n                                     -------------LAST LEVEL-------------          \n");
    printf("Cryptography is a method of protecting information and communications through the use of codes, so that only those \nfor whom the information is intended can read and process it.");
    printf(" One of the first ciphering technique is Caesar Cipher, \nin this, we shift the positions alphabets to encode the message. ");
    printf("For example, if the shift we used is 1, the cipher \ntext of HELLO will be IFMMP.\n\n");
    printf("However, this method was very easy to crack, which led to the development of new methods of encrypting the message. \n");
    printf("One method of ciphering the text is called Polyalphabetic Cipher, in this method, one secret shift word is shared, \nand the alphabets of the message are shifted as per the alphabet number in the shift word. ");
    printf("For example, if the shift \nword is GAME, then the shift in the message text would be 7 1 13 5 for consecutive letters, and this will repeat for \nthe whole message.\n\n");
    printf("But people also figured out how to crack this method, hence, again, a new method developed, called the One Time Pad. \n");
    printf("In this method, each alphabet of the message is shifted by a RANDOM number. \n\nPseudorandom numbers are quite interesting, aren't they?");

    /*Ciphering the word "success" as there are different random numbers displayed for same seed in different compilers, increasing
     the ascii value of alphabets by the number on ones digit in the respective pseudorandom number*/

    srand(7);
    for (int i = 0; i <= 6; i++)
    {
        int num = rand();
        num = num % 10;
        int ascii = word[i];
        ascii = ascii + num;
        char c = ascii;
        cipher[i] = c;
    }


    printf("\n\nNow, what you have to do is to crack this encrypted code    :   %s\nKEY   :   7\n", cipher);
    printf("REMEMBER, ITS ONLY THE ONES THAT MATTER!\n\n");

    //Giving some examples
    printf("Some encrypted examples of word 'hello' are - \n");

    for (int j = 3; j <= 5; j++)
    {
        char exp[5] = "hello", cipherexp[5] = "";

        printf("KEY = %d\n", j);

        printf("Pseudorandom numbers    :   ");

        for (int i = 0; i <= 4; i++)
        {
            int num1 = rand();
            printf("%d ", num1);
        }

        //Ciphering the word "hello"
        for (int i = 0; i <= 4; i++)
        {
            int num1 = rand();
            num1 = num1 % 10;
            int ascii = exp[i];
            ascii = ascii + num1;
            char c = ascii;
            cipherexp[i] = c;
        }
        printf("\nEncrypted message    :     %s\n\n", cipherexp);
    }

    printf("For your convenience, we will print 10 random numbers for you, all you have to do is give us the seed, but remember, \nyou will get only 5 chances!\n\n");

    int count = 5;
    while (count != 0)
    {
        int choice = 0;

        printf("Chances remaining   :   %d\n\n", count);
        printf("Want to display pseudorandom numbers? Enter 1 if yes, any other number if no    :   ");
        scanf("%d", &choice);

        count--;

        if (choice == 1)
        {
            int seed = 0;
            printf("Enter the seed  :   ");
            scanf("%d", &seed);

            srand(seed);

            printf("Pseudorandom numbers generated by the given seed are    -   \n");
            for (int i = 0; i <= 9; i++)
            {
                int num1 = rand();
                printf("%d ", num1);
            }
            printf("\n");
        }

        printf("Enter the answer    :   ");
        scanf("%s", &answer);

        //If the input answer matches the word "success", the loop will terminate, else it will continue until the given 5 chances are over
        if (strcmp(answer, "success") == 0)
        {
            break;
        }
        else
        {
            printf("Oh, oh, wrong answer :(");
        }
        printf("\n\n");

    }
    if (strcmp(answer, "success") == 0)
    {
        printf("\nWell done!! You have achieved |xihnz{ in cracking the code!\n");
    }
    else
    {
        printf("Sorry :( you lost the game!\n");
    }
    return 0;
}
